// dm viewer — builds .design-recall/viewer/index.html (single static file, data inlined) and viewer/sw.js.
// Usage from dm.js: require("./viewer").build({ ROOT, DM, SNAPSHOTS, decisions, findings, snapshot })
// Version files are not on disk as folders: snapshots/manifest.json maps each version's paths to blobs in
// snapshots/blobs/, and the service worker serves viewer/snap/<expl>/vNN/<path> from them. Service workers
// need http, so the viewer must be served (dm viewer --serve, or any static server over .design-recall/).
const fs = require("fs");
const path = require("path");

// by extension; blobs have none, so the service worker and dm viewer --serve both type responses from this
const MIME = {
  html: "text/html; charset=utf-8", htm: "text/html; charset=utf-8", css: "text/css; charset=utf-8",
  js: "text/javascript; charset=utf-8", mjs: "text/javascript; charset=utf-8", json: "application/json; charset=utf-8",
  svg: "image/svg+xml", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", gif: "image/gif", webp: "image/webp",
  avif: "image/avif", ico: "image/x-icon", woff: "font/woff", woff2: "font/woff2", ttf: "font/ttf", otf: "font/otf",
  mp4: "video/mp4", webm: "video/webm", mp3: "audio/mpeg", wav: "audio/wav", txt: "text/plain; charset=utf-8",
  md: "text/plain; charset=utf-8", xml: "application/xml", pdf: "application/pdf",
};

function build(ctx) {
  const { DM, SNAPSHOTS, decisions, findings, snapshot, principles = [] } = ctx;
  snapshot(); // refresh extracted versions
  let man = { versions: {} };
  try { man = JSON.parse(fs.readFileSync(path.join(SNAPSHOTS, "manifest.json"), "utf8")); } catch {}
  const versions = decisions.filter((d) => d.commit).map((d) => {
    const v = man.versions[d.exploration + "/v" + String(d.iteration).padStart(2, "0")];
    const pages = v ? Object.keys(v.files).filter((f) => /\.html?$/i.test(f)).sort() : [];
    return { ...d, pages };
  });
  const data = { generated: new Date().toISOString(), versions, findings, principles, explorations: [...new Set(versions.map((v) => v.exploration))] };
  const out = path.join(DM, "viewer");
  fs.mkdirSync(out, { recursive: true });
  // function replacement: a "$&" or "$1" inside a decision must not be read as a replace pattern
  fs.writeFileSync(path.join(out, "index.html"), HTML.replace("/*__DATA__*/", () => "const DATA = " + JSON.stringify(data) + ";"));
  fs.writeFileSync(path.join(out, "sw.js"), SW.replace("/*__MIME__*/", () => JSON.stringify(MIME)));
  return path.join(out, "index.html");
}

// Service worker (viewer/sw.js, scope viewer/): answers viewer/snap/<expl>/vNN/<path> from the manifest.
// The manifest is re-read on every page navigation, so a rebuild shows up on the next reload.
const SW = `// generated by design-recall — serves viewer/snap/<expl>/vNN/<path> from ../snapshots/{manifest.json,blobs/}
const MIME = /*__MIME__*/;
const BASE = new URL("../snapshots/", self.registration.scope);
const SNAP = new URL("snap/", self.registration.scope).pathname;
let manifest = null;
async function loadManifest() {
  const r = await fetch(new URL("manifest.json", BASE), { cache: "no-store" });
  if (!r.ok) throw new Error("manifest " + r.status);
  manifest = await r.json();
  return manifest;
}
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));
self.addEventListener("message", (e) => { if (e.data === "claim") e.waitUntil(self.clients.claim()); });
self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(SNAP)) return;
  e.respondWith(serve(url.pathname.slice(SNAP.length), e.request.mode === "navigate"));
});
async function serve(rest, fresh) {
  const notFound = (why) => new Response("design-recall: " + why, { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });
  let parts;
  try { parts = rest.split("/").map(decodeURIComponent); } catch { return notFound("bad path"); }
  if (parts.length < 3) return notFound("bad path");
  const tag = parts[0] + "/" + parts[1];
  let file = parts.slice(2).join("/");
  if (file === "" || file.endsWith("/")) file += "index.html";
  let m;
  try { m = fresh || !manifest ? await loadManifest() : manifest; } catch (err) { return notFound("cannot read snapshots/manifest.json (" + err.message + ") — run dm viewer"); }
  let v = m.versions[tag];
  if (!v || !v.files[file]) { try { m = await loadManifest(); v = m.versions[tag]; } catch {} }
  if (!v) return notFound("no snapshot for " + tag);
  const sha = v.files[file];
  if (!sha) return notFound(file + " is not in " + tag);
  const r = await fetch(new URL("blobs/" + sha, BASE));
  if (!r.ok) return notFound("blob " + sha + " missing — run dm viewer");
  const ext = (file.match(/\\.([^./]+)$/) || [])[1];
  return new Response(r.body, { headers: { "content-type": MIME[(ext || "").toLowerCase()] || "application/octet-stream", "cache-control": "no-cache" } });
}
`;

// Look: minimal, dark, high contrast, square corners, one accessible blue. Inter for the chrome, a mono
// face for ids/versions/timestamps. Sections sit on distinct shades (header darkest, stage lightest).
// Iterations render as a VS Code-style commit graph: newest on top, one line per version, forks as lanes.
const HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>design-recall viewer</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap">
<style>
:root{color-scheme:dark;
--bg0:#000;--bg1:#0b0b0b;--bg2:#121212;--bg3:#1a1a1a;--hov:#1e1e1e;--selbg:#0e2640;
--line:#262626;--line2:#3d3d3d;--fg:#f5f5f5;--mut:#a6a6a6;--dim:#8a8a8a;
--acc:#4da3ff;--accbg:#0b5cd5;--warn:#ffb020;--bad:#ff5c5c;--ok:#3ddc84;
--sans:Inter,"Inter var",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
--mono:"JetBrains Mono",ui-monospace,"Cascadia Mono",Consolas,monospace;
font-family:var(--sans);font-size:13px;line-height:1.45;color:var(--fg)}
*{box-sizing:border-box;border-radius:0!important;scrollbar-width:none}*::-webkit-scrollbar{display:none}
body{margin:0;background:var(--bg0);height:100vh;overflow:hidden;display:grid;grid-template-rows:40px minmax(0,1fr);grid-template-columns:300px 5px minmax(0,1fr) 5px 340px}
body.drag{cursor:col-resize;user-select:none}body.drag iframe{pointer-events:none}
:focus-visible{outline:2px solid var(--acc);outline-offset:-2px}
header{grid-column:1/-1;display:flex;gap:8px;align-items:center;padding:0 8px;background:var(--bg0);border-bottom:1px solid var(--line2);min-width:0;overflow:hidden}
header h1{font-size:13px;font-weight:600;letter-spacing:-.01em;margin:0 8px 0 4px;white-space:nowrap}
button,select{font:inherit;font-size:12px;height:26px;padding:0 10px;border:1px solid var(--line2);background:transparent;color:var(--fg);cursor:pointer;white-space:nowrap}
button:hover,select:hover{background:var(--hov)}select{background:var(--bg0)}option{background:var(--bg1)}
button.on{background:var(--accbg);border-color:var(--accbg);color:#fff}
.ic{width:26px;padding:0;display:inline-grid;place-items:center;color:var(--mut)}.ic:hover{color:var(--fg)}
.ic .fill{fill:currentColor}.ic[aria-pressed=false] .fill{fill:none}.ic[aria-pressed=true]{color:var(--fg)}
.chk{display:flex;gap:6px;align-items:center;font-size:12px;color:var(--mut);white-space:nowrap;cursor:pointer}.chk input{accent-color:var(--accbg);margin:0}
#pendCount{font-size:12px;color:var(--warn);white-space:nowrap}#live{font-size:11px;color:var(--warn);white-space:nowrap}
#gen{font-family:var(--mono);font-size:11px;color:var(--mut);white-space:nowrap}
aside{grid-row:2;overflow:auto;min-width:0}aside.l{grid-column:1;background:var(--bg1)}aside.r{grid-column:5;background:var(--bg2);padding:0 16px 20px}
body.nol aside.l,body.nor aside.r{display:none}
.rz{grid-row:2;background:var(--line);cursor:col-resize;touch-action:none}#rzL{grid-column:2}#rzR{grid-column:4}
.rz:hover,.rz:focus-visible,.rz.act{background:var(--acc);outline:0}
main{grid-column:3;grid-row:2;display:flex;flex-direction:column;min-width:0;background:var(--bg3)}
.pages{display:flex;flex:none;min-height:34px;background:var(--bg2);border-bottom:1px solid var(--line2);overflow-x:auto}
.pages button{border:0;border-right:1px solid var(--line);height:34px;font-family:var(--mono);font-size:12px;color:var(--mut)}
.pages button.on{background:var(--bg3);color:var(--fg);box-shadow:inset 0 -2px 0 var(--acc)}
.pages .empty{padding:9px 12px}
.frames{flex:1;display:flex;gap:1px;background:var(--line2);min-height:0}
.frames iframe{flex:1;border:0;background:#fff;width:100%;height:100%}
.nosw{flex:1;background:var(--bg2);padding:24px;max-width:none;font-size:13px}.nosw p{max-width:560px}.nosw pre{display:inline-block;margin:4px 0 12px}
.sec{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:0;padding:14px 12px 8px;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--mut)}
.sec .n{font-family:var(--mono);font-weight:400;letter-spacing:0;color:var(--dim)}
.sec button{height:22px;padding:0 6px;font-size:11px;font-weight:400;letter-spacing:0;text-transform:none;border-color:var(--line)}
.empty{padding:0 12px 8px;font-size:12px;color:var(--mut)}
.p{padding:6px 12px;cursor:pointer;border-left:2px solid transparent;font-size:12.5px}.p:hover{background:var(--hov)}
.p.on{border-left-color:var(--acc);background:var(--selbg)}.p.ret{color:var(--dim)}
.p b{font-family:var(--mono);font-weight:500;color:var(--acc);margin-right:6px}.p small{display:block;color:var(--mut);font-size:11px}
.graph{padding-bottom:16px}
.row{position:relative;cursor:pointer}
.row:hover{background:var(--hov)}.row.sel{background:var(--selbg);box-shadow:inset 2px 0 0 var(--acc)}
.row.cmp{box-shadow:inset 0 0 0 1px var(--warn)}.row.dim{opacity:.35}
.g{position:absolute;left:0;top:0;height:100%;overflow:visible}
.g .dot.s{fill:var(--selbg);stroke-width:2}
.ln{height:28px;display:flex;align-items:center;gap:8px;min-width:0}
.v{font-family:var(--mono);font-size:11.5px;color:var(--mut);flex:none}.row.sel .v{color:var(--acc)}
.c{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.mk{width:6px;height:6px;background:var(--warn);flex:none}
.tr{font-family:var(--mono);font-size:10.5px;line-height:16px;padding:0 4px;border:1px solid var(--line2);color:var(--mut);flex:none}
.x{border:0;height:28px;width:26px;padding:0;color:var(--mut);flex:none;font-size:11px}.x:hover{background:transparent;color:var(--fg)}
.more{display:none;padding:0 12px 12px 0;font-size:12.5px}.row.open .more{display:block}
.more p{margin:6px 0 0}.meta{font-family:var(--mono);font-size:11px;color:var(--mut)}
.lbl{color:var(--mut);font-size:11px}
.tag{display:inline-block;font-family:var(--mono);font-size:11px;line-height:18px;padding:0 6px;border:1px solid var(--line2);margin:4px 4px 0 0;cursor:pointer;color:var(--fg)}
.tag:hover{border-color:var(--fg)}.tag.on{background:var(--accbg);border-color:var(--accbg);color:#fff}
.inf{color:var(--warn)}.conf{color:var(--ok)}.st{font-family:var(--mono);font-size:11px}
.dh{padding:16px 0 0;margin:0;font-family:var(--mono);font-size:11.5px;font-weight:500;color:var(--acc)}
aside.r .sec{padding:20px 0 4px}
dl{margin:0}dt{margin-top:14px;font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--mut)}dd{margin:4px 0 0}
ul{margin:0;padding-left:16px}
pre{margin:0;white-space:pre-wrap;background:var(--bg0);border:1px solid var(--line);padding:8px 10px;font-family:var(--mono);font-size:12px}
code{font-family:var(--mono);font-size:11.5px}
.f{border-left:2px solid var(--line2);background:var(--bg1);padding:6px 10px;margin:8px 0;font-size:12.5px}
.f.high{border-color:var(--bad)}.f.medium{border-color:var(--warn)}.f.low{border-color:var(--mut)}
.mut{color:var(--mut)}
</style></head><body>
<header>
<button id="tglL" class="ic" title="Iterations panel ( [ )" aria-label="Show iterations panel" aria-pressed="true"><svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true"><rect x=".5" y=".5" width="13" height="13" fill="none" stroke="currentColor"/><rect class="fill" x="1" y="1" width="4" height="12"/></svg></button>
<h1>design-recall</h1>
<select id="expl" aria-label="Exploration"></select>
<button id="cmpBtn" title="Pick a second version to compare">Compare</button>
<label class="chk"><input type="checkbox" id="pendOnly"> pending only</label>
<span id="pendCount"></span>
<span style="flex:1"></span><span id="live"></span><span id="gen"></span>
<button id="reload" class="ic" title="Reload viewer ( R )" aria-label="Reload viewer">↻</button>
<button id="tglR" class="ic" title="Decision panel ( ] )" aria-label="Show decision panel" aria-pressed="true"><svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true"><rect x=".5" y=".5" width="13" height="13" fill="none" stroke="currentColor"/><rect class="fill" x="9" y="1" width="4" height="12"/></svg></button>
</header>
<aside class="l" aria-label="Principles and iterations"><div id="princ"></div><div id="tree"></div></aside>
<div class="rz" id="rzL" role="separator" aria-orientation="vertical" aria-label="Resize iterations panel" tabindex="0"></div>
<main><div class="pages" id="pages"></div><div class="frames" id="frames"></div></main>
<div class="rz" id="rzR" role="separator" aria-orientation="vertical" aria-label="Resize decision panel" tabindex="0"></div>
<aside class="r" id="ddr" aria-label="Decision record"></aside>
<script>
/*__DATA__*/
const $=s=>document.querySelector(s);const V=DATA.versions;
let expl=DATA.explorations[0],sel=null,cmp=null,picking=false,page=null,tagFilter=null,princ=null;
const open=new Set(); // ids of expanded iteration rows
const LANES=["#4da3ff","#3ddc84","#ff6bcb","#b58cff","#5ce1e6","#ffd24d"];const RH=28,MID=14,LW=14,LX=11;
const vkey=v=>v.exploration+"/v"+String(v.iteration).padStart(2,"0");
const vn=n=>"v"+String(n).padStart(2,"0");
const byExpl=e=>V.filter(v=>v.exploration===e).sort((a,b)=>a.iteration-b.iteration);
// storage can be missing (private windows, previews): every access is guarded
const ls={get(k,d){try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const ss={get(k){try{return sessionStorage.getItem(k)}catch(e){return null}},set(k,v){try{sessionStorage.setItem(k,v)}catch(e){}}};
function init(){
  $("#gen").textContent="built "+new Date(DATA.generated).toLocaleString();
  const s=$("#expl");DATA.explorations.forEach(e=>{const o=document.createElement("option");o.value=o.textContent=e;s.append(o)});
  const remembered=ss.get("dr.expl");if(remembered&&DATA.explorations.includes(remembered))expl=s.value=remembered;
  s.onchange=()=>{expl=s.value;ss.set("dr.expl",expl);sel=byExpl(expl).at(-1);cmp=null;page=null;render()};
  $("#cmpBtn").onclick=()=>{if(cmp){cmp=null;picking=false}else picking=!picking;render()};
  $("#pendOnly").onchange=render;
  const rs=ss.get("dr.sel");sel=byExpl(expl).find(v=>v.id===rs)||byExpl(expl).at(-1);
  layout();startSW();render();watchForRebuild();
}
// ---------- version files come from the service worker (viewer/sw.js); needs http, not file:// ----------
let swState="wait",swErr="";
function startSW(){
  const sw=navigator.serviceWorker;
  if(location.protocol==="file:"||!sw){swState="off";return}
  const ok=()=>{if(swState!=="ok"){swState="ok";frames()}};
  sw.addEventListener("controllerchange",ok);
  sw.register("sw.js",{updateViaCache:"none"}).then(()=>sw.ready).then(reg=>{
    // a hard reload bypasses the worker: ask it to claim this page again
    if(sw.controller)ok();else reg.active.postMessage("claim");
  }).catch(e=>{swState="err";swErr=e.message;frames()});
}
function swMsg(){
  const run='<pre>npx design-recall viewer --serve</pre>';
  if(swState==="off"&&location.protocol==="file:")return '<b>Open the viewer over http to see the mockups.</b><p>Version files are served by a service worker, which browsers only run over http. From the project root:</p>'+run+'<p class="mut">or serve the project with any static server (e.g. VS Code Live Server) and open <code>/.design-recall/viewer/</code>.</p>';
  if(swState==="off")return '<b>This browser has no service workers here.</b><p>They need a secure context: open the viewer on <code>localhost</code> (not a LAN address) or over https.</p>'+run;
  return '<b>The viewer\\'s service worker failed to start.</b><p>'+esc(swErr)+'</p>'+run;
}
// ---------- panels: show/hide + drag to resize (widths remembered per browser) ----------
const L=Object.assign({lw:300,rw:340,lh:false,rh:false},ls.get("dr.layout",{}));
function applyLayout(){
  const b=document.body;b.style.gridTemplateColumns=(L.lh?0:L.lw)+"px 5px minmax(0,1fr) 5px "+(L.rh?0:L.rw)+"px";
  b.classList.toggle("nol",L.lh);b.classList.toggle("nor",L.rh);
  $("#tglL").setAttribute("aria-pressed",String(!L.lh));$("#tglR").setAttribute("aria-pressed",String(!L.rh));
  $("#rzL").setAttribute("aria-valuenow",L.lh?0:L.lw);$("#rzR").setAttribute("aria-valuenow",L.rh?0:L.rw);
  ls.set("dr.layout",L);
}
function layout(){
  const toggle=s=>{L[s+"h"]=!L[s+"h"];applyLayout()};
  $("#tglL").onclick=()=>toggle("l");$("#tglR").onclick=()=>toggle("r");
  [["l",$("#rzL"),300],["r",$("#rzR"),340]].forEach(([s,el,def])=>{
    const max=()=>Math.round(innerWidth*.5);
    const setW=w=>{if(w<100)L[s+"h"]=true;else{L[s+"h"]=false;L[s+"w"]=Math.min(Math.max(w,180),max())}applyLayout()};
    el.onpointerdown=e=>{
      e.preventDefault();el.setPointerCapture(e.pointerId);el.classList.add("act");document.body.classList.add("drag");
      el.onpointermove=ev=>setW(s==="l"?ev.clientX:innerWidth-ev.clientX);
      el.onpointerup=el.onpointercancel=()=>{el.onpointermove=null;el.classList.remove("act");document.body.classList.remove("drag")};
    };
    el.ondblclick=()=>{L[s+"h"]=false;L[s+"w"]=def;applyLayout()};
    el.onkeydown=e=>{
      const grow=s==="l"?"ArrowRight":"ArrowLeft",shrink=s==="l"?"ArrowLeft":"ArrowRight",w=L[s+"h"]?0:L[s+"w"];
      if(e.key===grow){e.preventDefault();setW(Math.max(w,180)+20)}else if(e.key===shrink){e.preventDefault();setW(w-20)}
      else if(e.key==="Enter"){e.preventDefault();toggle(s)}
    };
    el.setAttribute("aria-valuemin",0);el.setAttribute("aria-valuemax",max());
  });
  document.addEventListener("keydown",e=>{
    if(e.metaKey||e.ctrlKey||e.altKey||/input|select|textarea/i.test(e.target.tagName))return;
    if(e.key==="[")toggle("l");else if(e.key==="]")toggle("r");else if(e.key==="r"||e.key==="R")location.reload();
  });
  applyLayout();
}
// ---------- commit graph ----------
// Newest first. Each lane holds the iteration it is waiting for (a parent); a version takes the first lane
// waiting for it, other lanes waiting for it curve in (a fork rejoining its parent), and its lane then waits
// for its own parent. before/after are the lanes crossing the top and bottom half of the row.
function graph(vs){
  const has=new Set(vs.map(v=>v.iteration));const lanes=[];let w=1;
  const rows=vs.slice().sort((a,b)=>b.iteration-a.iteration).map(v=>{
    const before=lanes.slice();const into=[];before.forEach((x,i)=>{if(x===v.iteration)into.push(i)});
    const free=lanes.indexOf(null);const col=into.length?into[0]:free>-1?free:lanes.length;
    into.forEach(i=>lanes[i]=null);lanes[col]=v.parent&&has.has(v.parent)?v.parent:null;
    while(lanes.length&&lanes[lanes.length-1]===null)lanes.pop();
    const after=lanes.slice();w=Math.max(w,before.length,after.length,col+1);
    return {v,col,before,after};
  });
  return {rows,width:LX*2+(w-1)*LW};
}
function svg(g,r,isSel){
  const x=i=>LX+i*LW,c=i=>LANES[i%LANES.length];let s="";
  const seg=(x1,y1,x2,y2,col)=>'<line x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'" stroke="'+col+'" stroke-width="2"/>';
  r.before.forEach((t,i)=>{if(t===null)return;
    if(t===r.v.iteration&&i!==r.col)s+='<path d="M'+x(i)+' 0 C'+x(i)+' '+MID*.8+' '+x(r.col)+' '+MID*.2+' '+x(r.col)+' '+MID+'" stroke="'+c(i)+'" stroke-width="2" fill="none"/>';
    else s+=seg(x(i),0,x(i),MID,c(i));
  });
  r.after.forEach((t,i)=>{if(t!==null)s+=seg(x(i),MID,x(i),"100%",c(i))});
  s+='<circle class="dot'+(isSel?' s':'')+'" cx="'+x(r.col)+'" cy="'+MID+'" r="'+(isSel?4.5:4)+'" fill="'+c(r.col)+'" stroke="'+c(r.col)+'" stroke-width="0"/>';
  return '<svg class="g" width="'+g.width+'" aria-hidden="true">'+s+'</svg>';
}
function choose(v){if(picking){cmp=v;picking=false}else{sel=v;if(cmp===v)cmp=null}ss.set("dr.sel",sel?sel.id:"");render()}
function tree(){
  const vs=byExpl(expl);const pend=$("#pendOnly").checked;const g=graph(vs);
  const t=$("#tree");const fid=document.activeElement&&document.activeElement.classList.contains("row")?document.activeElement.dataset.id:null;
  t.innerHTML='<h2 class="sec"><span>Iterations <span class="n">'+vs.length+'</span></span><span><button id="xall">expand all</button> <button id="call">collapse all</button></span></h2>';
  const list=document.createElement("div");list.className="graph";list.setAttribute("role","list");t.append(list);
  g.rows.forEach(r=>{
    const v=r.v;const isSel=sel===v,isOpen=open.has(v.id);
    // filters dim rather than hide, so the graph stays continuous
    const match=!(pend&&v.confidence!=="inferred")&&!(tagFilter&&!(v.tacit_tags||[]).includes(tagFilter))&&!(princ&&!(princ.evidence.includes(v.id)||princ.exceptions.includes(v.id)));
    const n=document.createElement("div");n.className="row"+(isSel?" sel":"")+(cmp===v?" cmp":"")+(isOpen?" open":"")+(match?"":" dim");
    n.dataset.id=v.id;n.tabIndex=0;n.setAttribute("role","listitem");if(isSel)n.setAttribute("aria-current","true");
    const rej=(v.rejected||[]).map(x=>esc(x.option)).join(", ");
    n.innerHTML=svg(g,r,isSel)+'<div style="padding-left:'+g.width+'px">'
      +'<div class="ln"><span class="v">'+vn(v.iteration)+'</span><span class="c" title="'+esc(v.change)+'">'+esc(v.change)+'</span>'
      +(v.confidence==="inferred"?'<span class="mk" title="inferred — awaiting rationale" aria-label="inferred"></span>':'')
      +(v.trigger&&v.trigger!=="designer"?'<span class="tr">'+esc(v.trigger)+'</span>':'')
      +'<button class="x" aria-expanded="'+isOpen+'" aria-label="'+(isOpen?"Collapse":"Expand")+' '+vn(v.iteration)+'">'+(isOpen?"▾":"▸")+'</button></div>'
      +'<div class="more"><div class="meta"><time datetime="'+esc(v.ts)+'">'+new Date(v.ts).toLocaleString()+'</time></div>'
      +'<p>'+esc(v.change)+'</p>'
      +'<p class="meta">'+esc(v.type)+' · '+esc(v.trigger)+' · <span class="'+(v.confidence==="inferred"?"inf":"conf")+'">'+esc(v.confidence)+'</span>'+(v.parent?' · from '+vn(v.parent):'')+'</p>'
      +'<p>'+(v.rationale?esc(v.rationale):'<span class="mut">no rationale recorded</span>')+'</p>'
      +(rej?'<p><span class="lbl">rejected</span> '+rej+'</p>':'')
      +((v.tacit_tags||[]).length?'<div>'+v.tacit_tags.map(x=>'<span class="tag">'+esc(x)+'</span>').join("")+'</div>':'')
      +'<p class="meta">'+esc(v.id)+' · '+esc(v.commit)+'</p></div></div>';
    n.onclick=e=>{if(e.target.closest(".x")){isOpen?open.delete(v.id):open.add(v.id);render();return}const tg=e.target.closest(".tag");if(tg){tagFilter=tagFilter===tg.textContent?null:tg.textContent;render();return}choose(v)};
    n.onkeydown=e=>{
      if(e.target!==n)return;
      if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(v)}
      else if(e.key==="ArrowRight"&&!isOpen){open.add(v.id);render()}
      else if(e.key==="ArrowLeft"&&isOpen){open.delete(v.id);render()}
      else if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();const s=e.key==="ArrowDown"?n.nextElementSibling:n.previousElementSibling;if(s)s.focus()}
    };
    list.append(n);
  });
  if(fid){const f=list.querySelector('[data-id="'+fid+'"]');if(f)f.focus()}
  $("#xall").onclick=()=>{vs.forEach(v=>open.add(v.id));render()};$("#call").onclick=()=>{open.clear();render()};
  const p=V.filter(v=>v.confidence==="inferred").length;$("#pendCount").textContent=p?p+" awaiting rationale":"";
  $("#cmpBtn").className=picking||cmp?"on":"";$("#cmpBtn").textContent=picking?"pick a version…":cmp?"Compare: off":"Compare";
}
function pages(){
  const el=$("#pages");el.innerHTML="";if(!sel)return;
  const list=sel.pages.length?sel.pages:[];if(!page||!list.includes(page))page=list.includes("index.html")?"index.html":list[0];
  list.forEach(pg=>{const b=document.createElement("button");b.textContent=pg;if(pg===page)b.className="on";b.onclick=()=>{page=pg;pages();frames()};el.append(b)});
  if(!list.length)el.innerHTML='<span class="empty">no html pages in snapshot — run dm viewer again</span>';
}
function src(v){return "snap/"+[v.exploration,vn(v.iteration)].concat(page.split("/")).map(encodeURIComponent).join("/")}
function frames(){
  const f=$("#frames");f.innerHTML="";if(!sel||!page)return;
  if(swState!=="ok"){f.innerHTML='<div class="nosw">'+(swState==="wait"?'loading…':swMsg())+'</div>';return}
  const a=document.createElement("iframe");a.src=src(sel);a.title=vkey(sel)+" "+page;f.append(a);
  if(cmp){const b=document.createElement("iframe");b.src=cmp.pages.includes(page)?src(cmp):"about:blank";b.title=vkey(cmp)+" "+page;f.append(b)}
}
function ddr(){
  const el=$("#ddr");if(!sel){el.innerHTML="";return}
  const v=sel;const fx=(DATA.findings||[]).filter(x=>x.exploration===v.exploration&&x.iteration===v.iteration);
  const rej=(v.rejected||[]).map(r=>"<li>"+esc(r.option)+(r.why?' <span class="mut">— '+esc(r.why)+"</span>":"")+"</li>").join("");
  const conf='<span class="st '+(v.confidence==="inferred"?"inf":"conf")+'">'+esc(v.confidence)+'</span>';
  el.innerHTML='<h2 class="dh">'+vkey(v)+' · '+esc(v.id)+'</h2><dl>'
   +'<dt>Change</dt><dd>'+esc(v.change)+'</dd>'
   +'<dt>Rationale</dt><dd>'+(v.rationale?esc(v.rationale):'<span class="mut">none recorded — ask the designer</span>')+' '+conf+'</dd>'
   +(rej?'<dt>Rejected</dt><dd><ul>'+rej+'</ul></dd>':'')
   +'<dt>Scope</dt><dd>'+(v.scope.page?esc(v.scope.page)+" · ":"")+(v.scope.components||[]).map(esc).join(", ")+'<br><code class="mut">'+(v.scope.files||[]).map(esc).join(", ")+'</code></dd>'
   +'<dt>Tags</dt><dd>'+((v.tacit_tags||[]).map(t=>'<span class="tag'+(tagFilter===t?" on":"")+'" data-t="'+esc(t)+'">'+esc(t)+'</span>').join("")||'<span class="mut">none</span>')+(tagFilter?' <span class="tag" data-t="">✕ clear</span>':'')+'</dd>'
   +'<dt>Parent · type · trigger · commit</dt><dd><code>'+(v.parent?vn(v.parent):"—")+' · '+esc(v.type)+' · '+esc(v.trigger)+' · '+esc(v.commit)+'</code></dd>'
   +(v.source_prompt?'<dt>Designer said</dt><dd><pre>'+esc(v.source_prompt)+'</pre></dd>':'')
   +'<dt>Recorded</dt><dd><code class="mut">'+new Date(v.ts).toLocaleString()+'</code></dd></dl>'
   +(fx.length?'<h2 class="sec">Critique findings <span class="n">'+fx.length+'</span></h2>'+fx.map(x=>'<div class="f '+esc(x.severity)+'"><b>'+esc(x.agent)+'</b> <code class="mut">'+esc(x.page||"")+' '+esc(x.component||"")+'</code><br>'+esc(x.finding)+(x.suggestion?'<br><span class="mut">→ '+esc(x.suggestion)+'</span>':'')+(x.status==="resolved"?' <span class="st conf">resolved</span>':'')+'</div>').join(""):"")
   +(princ?'<h2 class="sec">'+esc(princ.id)+' — '+esc(princ.title)+'</h2><p>'+esc(princ.statement)+'</p><p class="mut">evidence: '+princ.evidence.map(esc).join(", ")+(princ.exceptions.length?'<br>exceptions: '+princ.exceptions.map(esc).join(", "):'')+'</p>':'')
   +(cmp?'<h2 class="sec">Comparing with '+vkey(cmp)+'</h2><p>'+esc(cmp.change)+'</p><p class="mut">'+(cmp.rationale?esc(cmp.rationale):"no rationale")+'</p>':'');
  el.querySelectorAll(".tag").forEach(t=>t.onclick=()=>{tagFilter=t.dataset.t||null;render()});
}
function princs(){
  const el=$("#princ");const ps=DATA.principles||[];
  if(!ps.length){el.innerHTML='<h2 class="sec">Principles</h2><div class="empty">none yet — run <code>dm principles</code> via the design-principles skill</div>';return}
  el.innerHTML='<h2 class="sec"><span>Principles <span class="n">'+ps.length+'</span></span>'+(princ?'<button id="pclr">✕ clear</button>':'')+'</h2>'
    +ps.map((p,i)=>'<div class="p'+(princ===p?" on":"")+(p.retired?" ret":"")+'" data-i="'+i+'" tabindex="0" role="button" aria-pressed="'+(princ===p)+'"><b>'+esc(p.id)+'</b>'+esc(p.title)+(p.retired?' [retired]':'')+'<small>'+p.evidence.length+' decision'+(p.evidence.length===1?'':'s')+(p.exceptions.length?', '+p.exceptions.length+' exception'+(p.exceptions.length===1?'':'s'):'')+(p.kind?' · '+esc(p.kind):'')+'</small></div>').join("");
  el.querySelectorAll(".p").forEach(d=>{const go=()=>{const p=ps[+d.dataset.i];princ=princ===p?null:p;render()};d.onclick=go;d.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go()}}});
  const c=$("#pclr");if(c)c.onclick=()=>{princ=null;render()};
}
// Freshness: no background polling. When served over http, check for a newer build only when the tab
// regains focus (one GET, then idle); ↻ / R reloads on demand. Live Server-style tools already push
// reloads on file change; over file:// the button is the only option.
function watchForRebuild(){
  const el=$("#live");const btn=$("#reload");btn.onclick=()=>location.reload();
  if(location.protocol==="file:")return;
  const check=async()=>{try{const r=await fetch(location.href,{cache:"no-store"});const m=(await r.text()).match(/"generated":"([^"]+)"/);if(m&&m[1]!==DATA.generated){el.textContent="newer build available";btn.className="ic on"}}catch(e){}};
  document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")check()});
  window.addEventListener("focus",check);
}
function render(){princs();tree();pages();frames();ddr()}
function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
init();
</script></body></html>`;

module.exports = { build, MIME };
